# kubectl run my-nginx --image=nginx --port=80
# kubectl expose pod my-nginx --port=80 --type=LoadBalancer --load-balancer-ip=192.168.178.11
# kubectl delete pod my-nginx && kubectl delete service my-nginx
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.178.11-192.168.178.20
