apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pihole
  name: pihole-config
  namespace: pihole
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
