# https://github.com/pi-hole/docker-pi-hole/issues/862
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: pihole
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - image: pihole/pihole:2025.04.0
        imagePullPolicy: IfNotPresent
        name: pihole
        env:
        - name: FTLCONF_webserver_api_password
          valueFrom:
            secretKeyRef:
              key: password
              name: pihole-webpassword
        envFrom:
        - configMapRef:
            name: pihole-config
        resources:
          requests:
            memory: "80Mi"
          limits:
            memory: "100Mi"
        ports:
        - containerPort: 80
          name: pihole-http
          protocol: TCP
        - containerPort: 53
          name: pihole-dns-tcp
          protocol: TCP
        - containerPort: 53
          name: pihole-dns-udp
          protocol: UDP
        - containerPort: 443
          name: pihole-ssl
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/pihole
          name: config
      restartPolicy: Always
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: pihole-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflared
  name: cloudflared
  namespace: pihole
spec:
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: cloudflared
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - image: visibilityspots/cloudflared:v2025.4.0
        imagePullPolicy: IfNotPresent
        name: cloudflared
        ports:
        - containerPort: 5054
          name: dns
          protocol: TCP
        - containerPort: 5054
          name: dns-udp
          protocol: UDP
        - containerPort: 8080
          name: metrics
          protocol: TCP
        env:
        - name: TZ
          value: "Europe/Berlin"
